package dbsubnetgroup

import (
	agillv1alpha1 "github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1"
	"github.com/agill17/rds-operator/pkg/controller/lib"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/rds"
)

func (r *ReconcileDBSubnetGroup) createDBSubnetGroupInput(cr *agillv1alpha1.DBSubnetGroup) *rds.CreateDBSubnetGroupInput {
	subnetGroupInput := &rds.CreateDBSubnetGroupInput{
		DBSubnetGroupName:        &cr.Name,
		Tags:                     lib.GetTags(cr.GetLabels()),
		SubnetIds:                aws.StringSlice(cr.Spec.SubnetIds),
		DBSubnetGroupDescription: aws.String("This was generated by rds operator"),
	}
	return subnetGroupInput
}
