apiVersion: v1
kind: Namespace
metadata:
  name: amrit
---
apiVersion: agill.apps/v1alpha1
kind: DBInstance
metadata:
  name: mysql
  namespace: amrit
spec:
  engine: mysql
  engineVersion: 5.6.40
  az: us-east-1a
  autoMinorVersionUpgrade: false
  allocatedStorage: 20
  backupRetentionPeriod: 1
  dbInstanceClass: db.t2.micro
  dbName: mydb
  dBSecurityGroups: []
  dBSubnetGroupName: default
  deletionProtection: false
  storageEncrypted: false
  rehealFromLatestSnapshot: true
  dbSecretName: rds-db-secret
  externalSvcName: rds-endpoint
  masterUsername: admin
  masterPassword: password
  deletePolicy:
    deleteAutomatedBackups: true
    skipFinalSnapshot: true
  ## Optional
  initDBJob:
    waitTillCompleted: true
    timeout: 100 ## secs
    image: agill17/mysqltest
    sqlFile: "/docker-entrypoint-initdb.d/test.sql"
    ## Optional 
    # nodeSelector:
    #     key: val
    # imagePullSecret: yourSecretNameToUse
    