apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dbclusters.agill.apps
spec:
  group: agill.apps
  names:
    kind: DBCluster
    listKind: DBClusterList
    plural: dbclusters
    singular: dbcluster
  scope: Namespaced
  version: v1alpha1
