---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rds-operator
  namespace: rds-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rds-operator
  namespace: rds-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - agill.apps
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rds-operator
  namespace: rds-operator
subjects:
- kind: ServiceAccount
  name: rds-operator
  namespace: rds-operator
roleRef:
  kind: ClusterRole
  name: rds-operator
  apiGroup: rbac.authorization.k8s.io