apiVersion: v1
kind: Namespace
metadata:
  name: agill
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
  namespace: agill
type: Opaque
data:
  MASTER_USERNAME: cm9vdA==
  MASTER_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: agill.apps/v1alpha1
kind: DBCluster
metadata:
  name: aurora-cluster
  namespace: agill
region: us-east-1
spec:
  credentialsFrom:
    secret: 
      name: cluster-credentials
    usernameKey: MASTER_USERNAME
    passwordKey: MASTER_PASSWORD
  createClusterSpec:
    ## all available create fields
    # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBClusterInput
    Engine: aurora-mysql
    EngineMode: provisioned
    EngineVersion: 5.7.12
    AvailabilityZones: 
      - us-east-1a
      - us-east-1b
    BackupRetentionPeriod: 1
    DBClusterIdentifier: agill-aurora-cluster ## required
    DatabaseName: test
    DeletionProtection: false
    # MasterUsername: root # not required if credentialsFrom set ( if none passed: generates a random one if not passed )
    # MasterUserPassword: password # not required if credentialsFrom set ( if none passed: generates a random one if not passed )
    StorageEncrypted: false
  deleteClusterSpec:
    SkipFinalSnapshot: false
    DBClusterIdentifier: agill-aurora-cluster ## not required -- will be whatever is set inside createClusterSpec.DBClusterIdentifier
    # FinalDBSnapshotIdentifier: agill-aurora-cluster-snap ## not required ( will be namespace-crName-timestamp)

# ---
# apiVersion: agill.apps/v1alpha1
# kind: DBInstance
# metadata:
#   name: aurora-instance
#   namespace: agill
# spec:
#   serviceName: rds-instance-endpoint
#   createInstanceSpec:
#     ## all available create fields
#     # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceInput
#     AutoMinorVersionUpgrade: false
#     CopyTagsToSnapshot: true
#     DBClusterIdentifier: agill-aurora-cluster
#     DBInstanceIdentifier: agill-aurora-instance
#     AvailabilityZone: us-east-1a
#     Engine: aurora-mysql
#     MultiAZ: false
#     PubliclyAccessible: true
#     EngineVersion: 5.7.12
#     DBInstanceClass: db.t2.small
#   deleteInstanceSpec:
#     DeleteAutomatedBackups: false
#     SkipFinalSnapshot: false 

