apiVersion: v1
kind: Namespace
metadata:
  name: amrit
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
  namespace: amrit
type: Opaque
data:
  MASTER_USERNAME: cm9vdA==
  MASTER_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: agill.apps/v1alpha1
kind: DBCluster
metadata:
  name: aurora-cluster
  namespace: amrit
region: us-east-1
spec:
  serviceName: db-service
  credentialsFrom:
    secret: 
      name: cluster-credentials
    usernameKey: MASTER_USERNAME
    passwordKey: MASTER_PASSWORD
  createClusterSpec:
    ## all available create fields
    # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBClusterInput
    Engine: aurora-mysql
    EngineMode: provisioned
    EngineVersion: 5.7.12
    AvailabilityZones: 
      - us-east-1a
      - us-east-1b
    BackupRetentionPeriod: 1
    DBClusterIdentifier: amrit-aurora-cluster ## required
    DatabaseName: test
    DeletionProtection: false
    # MasterUsername: root # not required if credentialsFrom set ( if none passed: generates a random one if not passed )
    # MasterUserPassword: password # not required if credentialsFrom set ( if none passed: generates a random one if not passed )
    StorageEncrypted: false
  deleteClusterSpec:
    SkipFinalSnapshot: false
    DBClusterIdentifier: amrit-aurora-cluster ## not required -- will be whatever is set inside createClusterSpec.DBClusterIdentifier
    # FinalDBSnapshotIdentifier: amrit-aurora-cluster-snap ## not required ( will be namespace-crName-timestamp)
  # initClusterDB:
  #   jobSpec:
  #     backoffLimit: 6
  #     template: 
  #       spec:
  #         containers:
  #         - name: mysql
  #           image: mysql
  #           command: ["sh", "-c", "hello"]
---
apiVersion: agill.apps/v1alpha1
kind: DBInstance
metadata:
  name: aurora-instance
  namespace: amrit
spec:
  createInstanceSpec:
    ## all available create fields
    # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceInput
    AutoMinorVersionUpgrade: false
    CopyTagsToSnapshot: true
    DBClusterIdentifier: amrit-aurora-cluster
    DBInstanceIdentifier: amrit-aurora-instance
    AvailabilityZone: us-east-1a
    Engine: aurora-mysql
    MultiAZ: false
    PubliclyAccessible: true
    EngineVersion: 5.7.12
    DBInstanceClass: db.t2.small
  deleteInstanceSpec:
    DeleteAutomatedBackups: false
    SkipFinalSnapshot: false 

