apiVersion: v1
kind: Namespace
metadata:
  name: agill
---
apiVersion: agill.apps/v1alpha1
kind: DBCluster
metadata:
  name: aurora-cluster
  namespace: agill
clusterSecretName: cluster-secret # not required ( defaults to metadata.name-secret )
region: us-east-1
spec:
  createClusterSpec:
    ## all available create fields
    # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBClusterInput
    AvailabilityZones: 
      - us-east-1a
      - us-east-1b
    BackupRetentionPeriod: 1
    DBClusterIdentifier: aurora-postgres ## required
    DatabaseName: test
    DeletionProtection: false
    Engine: "aurora-postgresql"
    EngineMode: "provisioned"
    EngineVersion: 9.6.8
    # MasterUsername: root # not required ( generates a random one if not passed )
    # MasterUserPassword: password # not required ( generates a random one if not passed )
    StorageEncrypted: false
  deleteClusterSpec:
    SkipFinalSnapshot: false
    # DBClusterIdentifier: aurora-postgres ## not required -- will be whatever is set inside createClusterSpec.DBClusterIdentifier
    # FinalDBSnapshotIdentifier: aurora-postgres-snap ## not required ( will be namespace-crName-timestamp)
---
apiVersion: agill.apps/v1alpha1
kind: DBInstance
metadata:
  name: aurora-instance
  namespace: agill
spec:
  serviceName: rds-instance-endpoint
  createInstanceSpec:
    ## all available create fields
    # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceInput
    AutoMinorVersionUpgrade: false
    CopyTagsToSnapshot: true
    DBClusterIdentifier: aurora-postgres
    DBInstanceIdentifier: aurora-postgres-instance
    AvailabilityZone: us-east-1a
    Engine: "aurora-postgresql"
    MultiAZ: false
    PubliclyAccessible: true
    EngineVersion: 9.6.8
    DBInstanceClass: db.r4.large
  deleteInstanceSpec:
    DeleteAutomatedBackups: false
    SkipFinalSnapshot: false 

