apiVersion: v1
kind: Namespace
metadata:
  name: amritg
---
apiVersion: agill.apps/v1alpha1
kind: DBCluster
metadata:
  name: aurora-cluster
  namespace: amritg
clusterSecretName: cluster-secret # not required ( defaults to metadata.name-secret )
region: us-east-1
createClusterSpec:
  ## All create parameters available natively from aws sdk
  ## so this controller STRICTLY follows AWS parameter combination
  ## so ensure correct parameters are passed as per their doc and as per your requirement
  # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBClusterInput
  AvailabilityZones: 
    - us-east-1a
    - us-east-1b
  BackupRetentionPeriod: 1
  DBClusterIdentifier: amritg-aurora-cluster ## required
  DatabaseName: test
  DeletionProtection: false
  Engine: "aurora-mysql"
  EngineMode: "provisioned"
  EngineVersion: 5.7.12
  # MasterUsername: root # not required ( generates a random one if not passed )
  # MasterUserPassword: password # not required ( generates a random one if not passed )
  StorageEncrypted: false
deleteClusterSpec:
  ## All delete parameters available ( required vs not-required per aws )
  # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#DeleteDBClusterInput
  SkipFinalSnapshot: false
  DBClusterIdentifier: amritg-aurora-cluster ## not required -- will be whatever is set inside createClusterSpec.DBClusterIdentifier
  # FinalDBSnapshotIdentifier: amritg-aurora-cluster-snap ## not required ( will be namespace-crName-timestamp)
---
apiVersion: agill.apps/v1alpha1
kind: DBInstance
metadata:
  name: aurora-instance
  namespace: amritg
serviceName: rds-instance-endpoint
createInstanceSpec:
## All create parameters available natively from aws sdk
  ## so this controller STRICTLY follows AWS parameter combination
  ## so ensure correct parameters are passed as per their doc and as per your requirement
  # https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceInput
  AutoMinorVersionUpgrade: false
  CopyTagsToSnapshot: true
  DBClusterIdentifier: amritg-aurora-cluster
  DBInstanceIdentifier: amritg-aurora-instance
  AvailabilityZone: us-east-1a
  Engine: "aurora-mysql"
  MultiAZ: false
  PubliclyAccessible: true
  EngineVersion: 5.7.12
  DBInstanceClass: db.t2.small
deleteInstanceSpec:
  DeleteAutomatedBackups: false
  SkipFinalSnapshot: false 

