// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBCluster":           schema_pkg_apis_agill_v1alpha1_DBCluster(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBClusterSpec":       schema_pkg_apis_agill_v1alpha1_DBClusterSpec(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBClusterStatus":     schema_pkg_apis_agill_v1alpha1_DBClusterStatus(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBInstance":          schema_pkg_apis_agill_v1alpha1_DBInstance(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBInstanceSpec":      schema_pkg_apis_agill_v1alpha1_DBInstanceSpec(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBInstanceStatus":    schema_pkg_apis_agill_v1alpha1_DBInstanceStatus(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBSubnetGroup":       schema_pkg_apis_agill_v1alpha1_DBSubnetGroup(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBSubnetGroupSpec":   schema_pkg_apis_agill_v1alpha1_DBSubnetGroupSpec(ref),
		"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBSubnetGroupStatus": schema_pkg_apis_agill_v1alpha1_DBSubnetGroupStatus(ref),
	}
}

func schema_pkg_apis_agill_v1alpha1_DBCluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBCluster is the Schema for the dbclusters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBClusterSpec", "github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBClusterSpec defines the desired state of DBCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBClusterStatus defines the observed state of DBCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBInstance(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBInstance is the Schema for the dbinstances API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBInstanceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBInstanceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBInstanceSpec", "github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBInstanceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBInstanceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBInstanceSpec defines the desired state of DBInstance",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBInstanceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBInstanceStatus defines the observed state of DBInstance",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBSubnetGroup(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBSubnetGroup is the Schema for the dbsubnetgroups API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBSubnetGroupSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBSubnetGroupStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBSubnetGroupSpec", "github.com/agill17/rds-operator/pkg/apis/agill/v1alpha1.DBSubnetGroupStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBSubnetGroupSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBSubnetGroupSpec defines the desired state of DBSubnetGroup",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_agill_v1alpha1_DBSubnetGroupStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBSubnetGroupStatus defines the observed state of DBSubnetGroup",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
